AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation Template to deploy Lambda and ECS Fargate"

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "MyBackendLambda"
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: "Hello from Lambda!" })
            };
          };
      MemorySize: 128
      Timeout: 5

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  FargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "MyTask"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ECSExecutionRole
      ContainerDefinitions:
        - Name: "MyAppContainer"
          Image: "public.ecr.aws/nginx/nginx:latest"
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

Outputs:
  LambdaFunctionName:
    Description: "Lambda Function Name"
    Value: !Ref MyLambdaFunction
