AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation Template to deploy DynamoDB Table and RDS"

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Users"
      AttributeDefinitions:
        - AttributeName: "UserId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "UserId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: MyDB
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: Password123!
      MultiAZ: true  # Enabled Multi-AZ
      BackupRetentionPeriod: 7

Outputs:
  DynamoDBTable:
    Description: "DynamoDB Table Name"
    Value: !Ref MyDynamoDBTable
