AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation Template to deploy SQS and SNS"

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "MyAppQueue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AppNotifications"

Outputs:
  SQSQueue:
    Description: "SQS Queue Name"
    Value: !Ref MyQueue
